### ISSUE TITLE
python3 support 

### ISSUE THREAD

**Issue by martyzz1** [robinedwards/gitfeatures#13]
`Cloning git://github.com/robinedwards/gitfeatures.git to /private/var/folders/gm/ctpy57p17ljcv_xt0jh3sd0h0000gn/T/pip-build-b598dpn0/gitfeatures
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/gitfeatures.egg-info
    writing pip-egg-info/gitfeatures.egg-info/PKG-INFO
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/gm/ctpy57p17ljcv_xt0jh3sd0h0000gn/T/pip-build-b598dpn0/gitfeatures/setup.py", line 21, in <module>
        'scripts/git-releasecandidate'
      File "/Users/marty/sn-ap/sn-ap-drivers-app/pyenv/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/Users/marty/.pyenv/versions/3.6.5/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/marty/.pyenv/versions/3.6.5/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Users/marty/.pyenv/versions/3.6.5/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/marty/sn-ap/sn-ap-drivers-app/pyenv/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 271, in run
        writer(self, ep.name, os.path.join(self.egg_info, ep.name))
      File "/Users/marty/sn-ap/sn-ap-drivers-app/pyenv/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 604, in write_pkg_info
        metadata.write_pkg_info(cmd.egg_info)
      File "/Users/marty/.pyenv/versions/3.6.5/lib/python3.6/distutils/dist.py", line 1106, in write_pkg_info
        self.write_pkg_file(pkg_info)
      File "/Users/marty/sn-ap/sn-ap-drivers-app/pyenv/lib/python3.6/site-packages/setuptools/dist.py", line 91, in write_pkg_file
        long_desc = rfc822_escape(self.get_long_description())
      File "/Users/marty/.pyenv/versions/3.6.5/lib/python3.6/distutils/util.py", line 474, in rfc822_escape
        lines = header.split('\n')
    TypeError: a bytes-like object is required, not 'str'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/gm/ctpy57p17ljcv_xt0jh3sd0h0000gn/T/pip-build-b598dpn0/gitfeatures/
`

**Comment by robinedwards** [comment]
Hahaha hello! Hope you are well. Patches welcome :-)
